name: iStaffMode
main: Kurth\StaffMode
api: [4.0.0]
version: 1.0.0
author: iKurth
website: https://github.com/iKurth
permissions:
 staffmode.staff.cmd:
  default: op
  description: Always use this command
 staffmode.pinfo.cmd:
  default: op
  description: Always use this command
 staffmode.freeze.cmd:
  default: op
  description: Always use this command
 staffmode.chat.cmd:
  default: op
  description: Always use this command
 staffmode.join:
  default: op
  description: Always broadcast join and quit message