name: StaffMode
main: Kurth\StaffMode
api: [4.0.0]
version: 1.0.0
author: iKurth
website: https://github.com/iKurth
permissions:
 staff.use.join:
  description: Always broadcast message to join
 staffmode.use.cmd:
  description: Always use this command
  default: op
 staffchat.use.cmd:
  description: Always use this command
  default: op
 staffchat.use.view:
  description: Always view private messages
  default: op
 freeze.use.cmd:
  description: Always use this command
  default: op